/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-07-14 04:46:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.board.dto.BoardDto;
import java.util.List;

public final class boardlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1594691331482L));
    _jspx_dependants.put("jar:file:/C:/Users/User/workspace들/eclipse-semi/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semi_S/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.board.dto.BoardDto");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("UTF-8");

      out.write('\r');
      out.write('\n');

	response.setContentType("text/html; charset=UTF-8");

      out.write("    \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"manifest\" href=\"site.webmanifest\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS here -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/hamburgers.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/gijgo.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/animated-headline.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/slick.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/table.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/logostyle.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.table_th{\r\n");
      out.write("\t\tpadding: 20px 30px;\r\n");
      out.write("\t\tborder-bottom: 1px solid;\r\n");
      out.write("\t\tfont-size: 20pt;\r\n");
      out.write("\t}\r\n");
      out.write("\t.boardtitle{\r\n");
      out.write("\t\tcolor: blue;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");

	List<BoardDto> list = (List<BoardDto>)request.getAttribute("allList");

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" \t<!-- ? Preloader Start -->\r\n");
      out.write("    <div id=\"preloader-active\">\r\n");
      out.write("        <div class=\"preloader d-flex align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"preloader-inner position-relative\">\r\n");
      out.write("                <div class=\"preloader-circle\"></div>\r\n");
      out.write("                <div class=\"preloader-img pere-text\">\r\n");
      out.write("                    <img src=\"assets/img/logo/loder.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Preloader Start -->\r\n");
      out.write("    <div> \r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("    <!-- header end -->\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- Main -->\r\n");
      out.write("\t<main>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--? Hero Start -->\r\n");
      out.write("    <div class=\"slider-area2\">\r\n");
      out.write("        <div class=\"slider-height2 d-flex align-items-center\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-12\">\r\n");
      out.write("                        <div class=\"hero-cap hero-cap2 pt-70 text-center\">\r\n");
      out.write("                            <h2>자유게시판</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Hero End -->\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div style=\"padding:30px; height:800px;\">\r\n");
      out.write("\t<form action=\"BoardController\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"command\" value=\"boardwrite\">\r\n");
      out.write("\t\t<table border=\"3\">\r\n");
      out.write("\t\t\t<col width=\"50px\"><col width=\"100px\">\r\n");
      out.write("\t\t\t<col width=\"300px\"><col width=\"100px\"> \r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<th class=\"table_th\">NO</th>\r\n");
      out.write("\t\t\t\t<th class=\"table_th\">WRITER</th>\r\n");
      out.write("\t\t\t\t<th class=\"table_th\">TITLE</th>\r\n");
      out.write("\t\t\t\t<th class=\"table_th\">DATE</th>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t");

				if(list.size()==0){
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"5\">-----글이 존재하지 않습니다.-----</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				}else{
						for(BoardDto dto:list){
			
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(dto.getSeq() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(dto.getWriter() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td><a class=\"boardtitle\" href=\"BoardController?command=detail&seq=");
      out.print(dto.getSeq());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(dto.getTitle() );
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(dto.getRegdate() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");

					}
				}
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"4\" align=\"right\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"글쓰기\" >\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</main>\r\n");
      out.write("\t<div> \r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("    <!-- Scroll Up -->\r\n");
      out.write("    <div id=\"back-top\" >\r\n");
      out.write("        <a title=\"Go to Top\" href=\"#\"> <i class=\"fas fa-level-up-alt\"></i></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- JS here -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./assets/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("    <!-- Jquery, Popper, Bootstrap -->\r\n");
      out.write("    <script src=\"./assets/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- Jquery Mobile Menu -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Jquery Slick , Owl-Carousel Plugins -->\r\n");
      out.write("    <script src=\"./assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/slick.min.js\"></script>\r\n");
      out.write("    <!-- One Page, Animated-HeadLin -->\r\n");
      out.write("    <script src=\"./assets/js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/animated.headline.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Date Picker -->\r\n");
      out.write("    <script src=\"./assets/js/gijgo.min.js\"></script>\r\n");
      out.write("    <!-- Nice-select, sticky -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.sticky.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- counter , waypoint,Hover Direction -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/hover-direction-snake.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- contact js -->\r\n");
      out.write("    <script src=\"./assets/js/contact.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.form.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/mail-script.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Jquery Plugins, main Jquery -->\t\r\n");
      out.write("    <script src=\"./assets/js/plugins.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
