/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-07-15 03:20:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class It_005fnews_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title> IT NEWS </title>\r\n");
      out.write("<link rel=\"manifest\" href=\"site.webmanifest\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- CSS here -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/hamburgers.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/gijgo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/animated-headline.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/slick.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/posts.css\" />\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.table_th{\r\n");
      out.write("\t\tpadding: 20px 30px;\r\n");
      out.write("\t\tborder-bottom: 1px solid;\r\n");
      out.write("\t\tfont-size: 20pt;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\timg{\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#com {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    top:23px;\r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write("    #com :hover{\r\n");
      out.write("    \ttext-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("    #com1 {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    top:23px;\r\n");
      out.write("    }\r\n");
      out.write("    #com1 :hover{\r\n");
      out.write("    \ttext-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("    #com2{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    top:23px;\r\n");
      out.write("    }\r\n");
      out.write("    #com2 :hover{\r\n");
      out.write("    \ttext-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("    #com3{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    top:23px;\r\n");
      out.write("    }\r\n");
      out.write("    #com3 :hover{\r\n");
      out.write("    \ttext-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("    #com4{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    top:23px;\r\n");
      out.write("    }\r\n");
      out.write("    #com4 :hover{\r\n");
      out.write("    \ttext-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("    #com5{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    top:23px;\r\n");
      out.write("    }\r\n");
      out.write("    #com5 :hover{\r\n");
      out.write("    \ttext-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("    <body>\r\n");
      out.write(" \t<!-- ? Preloader Start -->\r\n");
      out.write("    <div id=\"preloader-active\">\r\n");
      out.write("        <div class=\"preloader d-flex align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"preloader-inner position-relative\">\r\n");
      out.write("                <div class=\"preloader-circle\"></div>\r\n");
      out.write("                <div class=\"preloader-img pere-text\">\r\n");
      out.write("                    <img src=\"assets/img/logo/loder.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Preloader Start -->\r\n");
      out.write("    <div> \r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("    <!-- header end -->\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- Main -->\r\n");
      out.write("\t<main>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--? Hero Start -->\r\n");
      out.write("    <div class=\"slider-area2\">\r\n");
      out.write("        <div class=\"slider-height2 d-flex align-items-center\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-12\">\r\n");
      out.write("                        <div class=\"hero-cap hero-cap2 pt-70 text-center\">\r\n");
      out.write("                            <h2>IT NEWS</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Hero End -->\r\n");
      out.write("       <div class=\"posts\">\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<a href=\"http://dpg.danawa.com/news/view?boardSeq=61&listSeq=4317482\" class=\"image\"><img src=\"assets/images/부품1.png\" alt=\"\" width=\"150\" height=\"250\" /></a>\r\n");
      out.write("\t\t\t<a href=\"http://dpg.danawa.com/news/view?boardSeq=61&listSeq=4317482\">\r\n");
      out.write("\t\t\t <div>\r\n");
      out.write("         <p id=\"com\"><strong>STCOM, 초소형 폼팩터 싱글 보드 컴퓨터 'ASUS Tinker Edge R' 출시</strong></p>\r\n");
      out.write("      </div>\r\n");
      out.write("      </a>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<a href=\"http://dpg.danawa.com/news/view?boardSeq=61&listSeq=4317460\" class=\"image\"><img src=\"assets/images/키보드.png\" alt=\"\" width=\"150\" height=\"250\" /></a>\r\n");
      out.write("\t\t\t<a href=\"http://dpg.danawa.com/news/view?boardSeq=61&listSeq=4317460\">\r\n");
      out.write("\t\t\t <div>\r\n");
      out.write("         <p id=\"com1\"><strong>피씨디렉트, 독일 감성의 '체리 MX Board 3.0 S 화이트 에디션 기계식 키보드' 출시</strong></p>\r\n");
      out.write("      </div>\r\n");
      out.write("      </a>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<a href=\"http://dpg.danawa.com/news/view?boardSeq=61&listSeq=4317480\" class=\"image\"><img src=\"assets/images/파워.png\" alt=\"\" width=\"150\" height=\"250\" /></a>\r\n");
      out.write("\t\t\t<a href=\"http://dpg.danawa.com/news/view?boardSeq=61&listSeq=4317480\">\r\n");
      out.write("\t\t\t <div>\r\n");
      out.write("         <p id=\"com2\"><strong>프리플로우, 80PLUS PLATINUM 규격 '델타 GPS-1000DB' 파워 출시</strong></p>\r\n");
      out.write("      </div>\r\n");
      out.write("      </a>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<a href=\"http://dpg.danawa.com/news/view?boardSeq=61&listSeq=4296830\" class=\"image\"><img src=\"assets/images/부품.png\" alt=\"\" width=\"150\" height=\"250\" /></a>\r\n");
      out.write("\t\t\t<a href=\"http://dpg.danawa.com/news/view?boardSeq=61&listSeq=4296830\">\r\n");
      out.write("\t\t\t <div>\r\n");
      out.write("         <p id=\"com3\"><strong>서린씨앤아이, 고성능 게이밍 메모리 '팀그룹 티포스 델타 RGB' 신제품 6종 출시</strong></p>\r\n");
      out.write("      </div>\r\n");
      out.write("      </a>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<a href=\"http://dpg.danawa.com/news/view?boardSeq=61&listSeq=4317453\" class=\"image\"><img src=\"assets/images/부품4.png\" alt=\"\" width=\"150\" height=\"250\" /></a>\r\n");
      out.write("\t\t\t<a href=\"http://dpg.danawa.com/news/view?boardSeq=61&listSeq=4317453\">\r\n");
      out.write("\t\t\t <div>\r\n");
      out.write("         <p id=\"com4\"><strong>STCOM, ITX 규격 AMD B550 메인보드 'ASUS ROG STRIX B550-I GAMING' 출시</strong></p>\r\n");
      out.write("      </div>\r\n");
      out.write("      </a>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<a href=\"http://dpg.danawa.com/news/view?boardSeq=61&listSeq=4283840\" class=\"image\"><img src=\"assets/images/rgb.png\" alt=\"\" width=\"150\" height=\"250\" /></a>\r\n");
      out.write("\t\t\t<a href=\"http://dpg.danawa.com/news/view?boardSeq=61&listSeq=4283840\">\r\n");
      out.write("\t\t\t <div>\r\n");
      out.write("         <p id=\"com5\"><strong>서린씨앤아이, 티포스 델타 RGB 라인업 신제품 공개</strong></p>\r\n");
      out.write("      </div>\r\n");
      out.write("      </a>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t</div>\r\n");
      out.write("    </main>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <!-- Footer Start-->\r\n");
      out.write("        <div class=\"footer-area footer-padding section-bg\" data-background=\"assets/img/gallery/footer_bg.png\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- Footer Top -->\r\n");
      out.write("                <div class=\"footer-top\">\r\n");
      out.write("                    <div class=\"row justify-content-between\">\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-3 col-md-5 col-sm-6\">\r\n");
      out.write("                            <div class=\"single-footer-caption mb-50\">\r\n");
      out.write("                                <div class=\"single-footer-caption mb-30\">\r\n");
      out.write("                                    <!-- logo -->\r\n");
      out.write("                                    <div class=\"footer-logo\">\r\n");
      out.write("                                        <a href=\"index.html\"><img src=\"assets/img/logo/logo2_footer.png\" alt=\"\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"footer-tittle\">\r\n");
      out.write("                                        <div class=\"footer-pera\">\r\n");
      out.write("                                            <p>Consectetur adipisicinhg cvelicsed do eiusmod tempor inciducvccnt ut labosvrer adipisic.</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-2 col-lg-3 col-md-3 col-sm-5\">\r\n");
      out.write("                            <div class=\"single-footer-caption mb-50\">\r\n");
      out.write("                                <div class=\"footer-tittle\">\r\n");
      out.write("                                    <h4>Quick Links</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">About</a></li>\r\n");
      out.write("                                        <li><a href=\"#\"> Offers & Discounts</a></li>\r\n");
      out.write("                                        <li><a href=\"#\"> Get Coupon</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">  Contact Us</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-3 col-md-4 col-sm-7\">\r\n");
      out.write("                            <div class=\"single-footer-caption mb-50\">\r\n");
      out.write("                                <div class=\"footer-tittle\">\r\n");
      out.write("                                    <h4>New Products</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">Woman Cloth</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Fashion Accessories</a></li>\r\n");
      out.write("                                        <li><a href=\"#\"> Man Accessories</a></li>\r\n");
      out.write("                                        <li><a href=\"#\"> Rubber made Toys</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-3 col-md-5 col-sm-7\">\r\n");
      out.write("                            <div class=\"single-footer-caption mb-50\">\r\n");
      out.write("                                <div class=\"footer-tittle\">\r\n");
      out.write("                                    <h4>Support</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">Frequently Asked Questions</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Terms & Conditions</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Report a Payment Issue</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Footer bottom -->\r\n");
      out.write("                <div class=\"footer-bottom\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xl-7 col-lg-8 col-md-7\">\r\n");
      out.write("                            <div class=\"footer-copy-right\">\r\n");
      out.write("                                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>                   \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-5 col-lg-4 col-md-5\">\r\n");
      out.write("                            <div class=\"footer-copy-right f-right\">\r\n");
      out.write("                                <!-- social -->\r\n");
      out.write("                                <div class=\"footer-social\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                    <a href=\"https://www.facebook.com/sai4ull\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fab fa-behance\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fas fa-globe\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Footer End-->\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Scroll Up -->\r\n");
      out.write("    <div id=\"back-top\" >\r\n");
      out.write("        <a title=\"Go to Top\" href=\"#\"> <i class=\"fas fa-level-up-alt\"></i></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- JS here -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./assets/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("    <!-- Jquery, Popper, Bootstrap -->\r\n");
      out.write("    <script src=\"./assets/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- Jquery Mobile Menu -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Jquery Slick , Owl-Carousel Plugins -->\r\n");
      out.write("    <script src=\"./assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/slick.min.js\"></script>\r\n");
      out.write("    <!-- One Page, Animated-HeadLin -->\r\n");
      out.write("    <script src=\"./assets/js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/animated.headline.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Date Picker -->\r\n");
      out.write("    <script src=\"./assets/js/gijgo.min.js\"></script>\r\n");
      out.write("    <!-- Nice-select, sticky -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.sticky.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- counter , waypoint,Hover Direction -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/hover-direction-snake.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- contact js -->\r\n");
      out.write("    <script src=\"./assets/js/contact.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.form.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/mail-script.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Jquery Plugins, main Jquery -->\t\r\n");
      out.write("    <script src=\"./assets/js/plugins.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
