/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-07-15 05:15:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Low_005fSpec_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title> Architects | Template </title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link rel=\"manifest\" href=\"site.webmanifest\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- CSS here -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/hamburgers.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/gijgo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/animated-headline.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/slick.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/logostyle.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t.low_all{\r\n");
      out.write("\t\t\twidth: 100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.low_img{\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tpadding: 10px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.low_detail{\r\n");
      out.write("\t\t\tfloat:right;\r\n");
      out.write("\t\t\twidth:650px;\r\n");
      out.write("\t\t\theight:350px;\r\n");
      out.write("\t\t\tpadding-top: 10px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.content{\r\n");
      out.write("\t\t\tclear: both;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tli{\r\n");
      out.write("\t\t\tpadding-bottom: 20px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#choose1\").hide();\r\n");
      out.write("\t\t$(\"#choose2\").hide();\r\n");
      out.write("\t\t$(\"#choose3\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction choose(num){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(num==1){\r\n");
      out.write("\t\t\t$(\"#choose1\").show();\r\n");
      out.write("\t\t\t$(\"#choose2\").hide();\r\n");
      out.write("\t\t\t$(\"#choose3\").hide();\r\n");
      out.write("\t\t}else if(num==2){\r\n");
      out.write("\t\t\t$(\"#choose1\").hide();\r\n");
      out.write("\t\t\t$(\"#choose2\").show();\r\n");
      out.write("\t\t\t$(\"#choose3\").hide();\r\n");
      out.write("\t\t}else if(num==3){\r\n");
      out.write("\t\t\t$(\"#choose1\").hide();\r\n");
      out.write("\t\t\t$(\"#choose2\").hide();\r\n");
      out.write("\t\t\t$(\"#choose3\").show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- ? Preloader Start -->\r\n");
      out.write("    <div id=\"preloader-active\">\r\n");
      out.write("        <div class=\"preloader d-flex align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"preloader-inner position-relative\">\r\n");
      out.write("                <div class=\"preloader-circle\"></div>\r\n");
      out.write("                <div class=\"preloader-img pere-text\">\r\n");
      out.write("                    <img src=\"assets/img/logo/loder.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Preloader Start -->\r\n");
      out.write("    <div> \r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("    <!-- header end -->\r\n");
      out.write("    <main>\r\n");
      out.write("    <!--? Hero Start -->\r\n");
      out.write("    <div class=\"slider-area2\">\r\n");
      out.write("        <div class=\"slider-height2 d-flex align-items-center\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-12\">\r\n");
      out.write("                        <div class=\"hero-cap hero-cap2 pt-70 text-center\">\r\n");
      out.write("                            <h2>PC 추천 - 저사양</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   <br><br>\r\n");
      out.write("   <!-- 사양별 태그 -->\r\n");
      out.write("   <section>   \r\n");
      out.write("   \t <!-- Section Tittle -->\r\n");
      out.write("   \t <article id=\"title\" align=\"center\">\r\n");
      out.write("   \t  <div>\r\n");
      out.write("          <div class=\"title\">\r\n");
      out.write("\t\t\t<button onclick=\"choose(1);\"><h1>CHOOSE - 1</h1></button>\r\n");
      out.write("\t\t\t<button onclick=\"choose(2);\"><h1>CHOOSE - 2</h1></button>\r\n");
      out.write("\t\t\t<button onclick=\"choose(3);\"><h1>CHOOSE - 3</h1></button>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   \t </article>\r\n");
      out.write("   \t<br>\r\n");
      out.write("\t<div class=\"container\" id=\"choose1\">\r\n");
      out.write("   \t   <div class=\"low_all\">\r\n");
      out.write("       \t<p class=\"low_img\">\r\n");
      out.write("       \t\t <img src=\"assets/img/gallery/popular1.png\" alt=\"\" width=\"500px;\" height=\"500px;\">\r\n");
      out.write("       \t</p>\r\n");
      out.write("       \t<div class=\"low_detail\">\r\n");
      out.write("       \t<sction>\r\n");
      out.write("         <div style=\"padding-left:100px;\">\r\n");
      out.write("          <div class=\"single_sidebar_widget post_category_widget\" style=\"width:600px; float:left;\">\r\n");
      out.write("            <ul class=\"list cat-list\">\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>CPU</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("                  \r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>메인보드</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>그래픽</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>ssd</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>ram</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>코로나</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("         </div>\r\n");
      out.write("        </sction>\r\n");
      out.write("       \t</div>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"container\" id=\"choose2\">\r\n");
      out.write("   \t   <div>\r\n");
      out.write("       \t<p class=\"low_img\">\r\n");
      out.write("       \t\t <img src=\"assets/img/gallery/popular2.png\" alt=\"\" width=\"500px;\" height=\"500px;\">\r\n");
      out.write("       \t</p>\r\n");
      out.write("       \t<div class=\"low_detail\">\r\n");
      out.write("       \t<sction>\r\n");
      out.write("         <div style=\"padding-left:100px;\">\r\n");
      out.write("          <div class=\"single_sidebar_widget post_category_widget\" style=\"width:600px; float:left;\">\r\n");
      out.write("            <ul class=\"list cat-list\">\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>CPU</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("                  \r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>메인보드</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>그래픽</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>ssd</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>ram</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>코로나</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("         </div>\r\n");
      out.write("        </sction>\r\n");
      out.write("       \t</div>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"container\" id=\"choose3\">\r\n");
      out.write("   \t   <div>\r\n");
      out.write("       \t<p class=\"low_img\">\r\n");
      out.write("       \t\t <img src=\"assets/img/gallery/popular3.png\" alt=\"\" width=\"500px;\" height=\"500px;\">\r\n");
      out.write("       \t</p>\r\n");
      out.write("       \t<div class=\"low_detail\">\r\n");
      out.write("       \t<sction>\r\n");
      out.write("         <div style=\"padding-left:100px;\">\r\n");
      out.write("          <div class=\"single_sidebar_widget post_category_widget\" style=\"width:600px; float:left;\">\r\n");
      out.write("            <ul class=\"list cat-list\">\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>CPU</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("                  \r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>메인보드</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>그래픽</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>ssd</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>ram</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\" class=\"d-flex\">\r\n");
      out.write("                     <p>코로나</p>\r\n");
      out.write("                     <p>(10)</p>\r\n");
      out.write("                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"text\" value=\"안녕하세요하하하하\">\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("         </div>\r\n");
      out.write("        </sction>\r\n");
      out.write("       \t</div>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"content\"></div>\r\n");
      out.write("  \t</section>\r\n");
      out.write("  \t<sction class=\"content\">\r\n");
      out.write("        \r\n");
      out.write("    <sction>\r\n");
      out.write("    </main>\r\n");
      out.write("    <div class=\"content\"></div>\r\n");
      out.write("    <div> \r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("    <!-- Scroll Up -->\r\n");
      out.write("    <div id=\"back-top\" >\r\n");
      out.write("        <a title=\"Go to Top\" href=\"#\"> <i class=\"fas fa-level-up-alt\"></i></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- JS here -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./assets/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("    <!-- Jquery, Popper, Bootstrap -->\r\n");
      out.write("    <script src=\"./assets/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- Jquery Mobile Menu -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Jquery Slick , Owl-Carousel Plugins -->\r\n");
      out.write("    <script src=\"./assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/slick.min.js\"></script>\r\n");
      out.write("    <!-- One Page, Animated-HeadLin -->\r\n");
      out.write("    <script src=\"./assets/js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/animated.headline.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Date Picker -->\r\n");
      out.write("    <script src=\"./assets/js/gijgo.min.js\"></script>\r\n");
      out.write("    <!-- Nice-select, sticky -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.sticky.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- counter , waypoint,Hover Direction -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/hover-direction-snake.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- contact js -->\r\n");
      out.write("    <script src=\"./assets/js/contact.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.form.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/mail-script.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Jquery Plugins, main Jquery -->\t\r\n");
      out.write("    <script src=\"./assets/js/plugins.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
