/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-07-15 05:44:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class wordcho2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title> Architects | Template </title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link rel=\"manifest\" href=\"site.webmanifest\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- CSS here -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/hamburgers.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/gijgo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/animated-headline.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/slick.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/posts.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- ? Preloader Start -->\r\n");
      out.write("    <div id=\"preloader-active\">\r\n");
      out.write("        <div class=\"preloader d-flex align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"preloader-inner position-relative\">\r\n");
      out.write("                <div class=\"preloader-circle\"></div>\r\n");
      out.write("                <div class=\"preloader-img pere-text\">\r\n");
      out.write("                    <img src=\"assets/img/logo/loder.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Preloader Start -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <!--? Header Start -->\r\n");
      out.write("        <div class=\"header-area header-transparent\">\r\n");
      out.write("            <div class=\"main-header header-sticky\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                        <!-- Logo -->\r\n");
      out.write("                        <div class=\"col-xl-2 col-lg-2 col-md-1\">\r\n");
      out.write("                            <div class=\"logo\">\r\n");
      out.write("                                <a href=\"index.html\"><img src=\"assets/img/logo/logo.png\" alt=\"\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-9 col-lg-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main-menu black-menu menu-bg-white d-none d-lg-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"hamburger hamburger--collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"hamburger-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"hamburger-inner\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<nav class=\"hamburger-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul id=\"navigation\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Tutorial</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"submenu\">\r\n");
      out.write("                                                <li><a href=\"wordcho.html\">초급</a></li>\r\n");
      out.write("                                                <li><a href=\"wordmid.html\">중급</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Guide</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"submenu\">\r\n");
      out.write("                                                <li><a href=\"#\">부품별 추천</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">가격비교</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Community</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"submenu\">\r\n");
      out.write("                                                <li><a href=\"#\">Q&A</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">IT news</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">login?</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                        <!-- Mobile Menu -->\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"mobile_menu d-block d-lg-none\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Header End -->\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- header end -->\r\n");
      out.write("    <main>\r\n");
      out.write("        <!--? Hero Start -->\r\n");
      out.write("        <div class=\"slider-area2\">\r\n");
      out.write("            <div class=\"slider-height2 d-flex align-items-center\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xl-12\">\r\n");
      out.write("                            <div class=\"hero-cap hero-cap2 pt-70 text-center\">\r\n");
      out.write("                                <h2>컴퓨터 초급 용어</h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Hero End -->\r\n");
      out.write("       <div class=\"posts\">\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"image\"><img src=\"assets/images/초급 -CPU.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t<h2>CPU</h2>\r\n");
      out.write("\t\t\t<p><i>모든 작동 연산을 담당하는 핵심 두뇌</i><br>사람으로 치면 두뇌에 해당하고 컴퓨터의 전반적인 성능을 좌우하는 가장 중요한 부품입니다\r\n");
      out.write("코어: CPU의 중심, 코어가 2개면 듀얼코어, 4개면 쿼드코어, 6개면 헥사 코어, 8개면 옥타코어\r\n");
      out.write("클럭: CPU가 일처리를 얼마나 빠르게 처리 하는지 GHz로 표시하는 것. 숫자가 클 수록 동작을 빠르게 처리합니다.\r\n");
      out.write("스레드: 보통 코어 개수와 동일하며 개수가 많을 수록 작업을 동시에 처리할 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("\t\t\t\t<details>\r\n");
      out.write("\t\t\t\t\t<summary>추천브랜드</summary>\r\n");
      out.write("\t\t\t\t\t<p>AMD, Intel</p>\r\n");
      out.write("\t\t\t\t</details>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"image\"><img src=\"assets/images/초급 -메인.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t<h2>메인보드</h2>\r\n");
      out.write("\t\t\t<p><i>각 하드웨어를 하나로 연결하는 기판</i><br>CPU,GPU,HDD,RAM등 내부 구성요소들이 유기적으로 연결될 수 있는 고리 역할을 담당한다.\r\n");
      out.write("쓸만한 제품은 가격도 비싸고 고장 시 교체도 가장 까다롭기 때문에 보통 품질이 보증되지 않은 5만원 이하 저가 모델은피하는 것이 좋다.\r\n");
      out.write("</p>\r\n");
      out.write("\t\t\t\t<details>\r\n");
      out.write("\t\t\t\t\t<summary>추천모델</summary>\r\n");
      out.write("\t\t\t\t\t<p>AUS, GIGABYTE, MSI</p>\r\n");
      out.write("\t\t\t\t</details>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"image\"><img src=\"assets/images/초급 -RAM.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t<h2>메모리(RAM)</h2>\r\n");
      out.write("\t\t\t<p><i>프로그램 구동에 필요한 자원</i><br>HDD나 SSD에 저장된 자료를 구동할 때 필요한 여유 자원을 제공합니다\r\n");
      out.write("흔히 '다다익램'이라 하여 램 용량은 크면 클수록 좋다고 하는데요. 어느 정도 맞는 말이긴 하지만\r\n");
      out.write("그래도 자신의 사용 범위에 꼭 필요한 수준만 구입하는 게 역시 현명한 소비자의 모습이겠지요?\r\n");
      out.write("</p>\r\n");
      out.write("\t\t\t\t<details>\r\n");
      out.write("\t\t\t\t\t<summary>적정범위</summary>\r\n");
      out.write("\t\t\t\t\t<p>사무용: 4-8GB, 게임용: 16GB 영상용: 16GB*2</p>\r\n");
      out.write("\t\t\t\t</details>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"image\"><img src=\"assets/images/초급 -SSD.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t<h2>HDD & SSD</h2>\r\n");
      out.write("\t\t\t<p><i>싸고 고용량 or 비싸지만 고속</i><br>HDD는 저렴하고 용량이 큰 장점과 소음이 있다는 단점을 가지고 있고 SSD는 가격이 꽤 나가지만 빠르고 소음이 적다는 장점을 가지고 있습니다.\r\n");
      out.write("보통의 가정집에선 HDD를 달고 게임용은 SSD를 추가적으로 달고 있습니다.\r\n");
      out.write("</p>\r\n");
      out.write("\t\t\t<details>\r\n");
      out.write("\t\t\t\t\t<summary>추천모델</summary>\r\n");
      out.write("\t\t\t\t\t<p>삼성전자 860 EVO</p>\r\n");
      out.write("\t\t\t\t</details>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"image\"><img src=\"assets/images/초급 -GPU.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t<h2>그래픽카드</h2>\r\n");
      out.write("\t\t\t<p><i>고성능 게임, 그래픽 작업에 필수</i><br>보통 그래픽카드와 명칭을 혼용하는 GPU는 사실 필수 하드웨어가 아닙니다. 요즘 CPU는 자체 GPU를 내장하고 있어 고사양 게임, 그래픽 작업용 PC가 아니라면 별도의 GPU는 불필요하기 때문인데요. 게임이나 고급 작업을 위한 사용자는 추가로 달아주면 됩니다.</p>\r\n");
      out.write("\t\t\t<details>\r\n");
      out.write("\t\t\t\t<summary>추천브랜드</summary>\r\n");
      out.write("\t\t\t\t<p>Geforce GTX 1060Ti</p>\r\n");
      out.write("\t\t\t</details>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"image\"><img src=\"assets/images/초급 -POWER.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t<h2>파워</h2>\r\n");
      out.write("\t\t\t<p><i>모든 하드웨어 직동에 필요한 전력을 공급하는 개체</i><br>\r\n");
      out.write("파워(Power)는 각 부품에 전력을 공급하는 장치입니다. 컴퓨터의 심장이라고 불리는 만큼 파워는 내부 모든 요소에 전류를 공급하는 핵심 장비이기때문에 너무 저품질 파워를 사용하게될 경우 짧은 수명을 갖게될 수 밖에 없습니다.\r\n");
      out.write("</p>\r\n");
      out.write("\t\t\t<details>\r\n");
      out.write("\t\t\t\t\t<summary>추천브랜드</summary>\r\n");
      out.write("\t\t\t\t\t<p>마이크로닉스 Classic II 600W</p>\r\n");
      out.write("\t\t\t</details>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"image\"><img src=\"assets/images/초급 -c.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t<h2>쿨러</h2>\r\n");
      out.write("\t\t\t<p> <i>CPU 과열 방지, 케이스 내부 온도 조절</i><br>\r\n");
      out.write("\t\t\t쿨러는 CPU작동 시 열을 식혀주는 역할을 합니다. 보통 냉각수 없는 공랭식이 사용되며, 요즘은 CPU 구매 시 번들로 함께 제공되는 기본 쿨러도 있습니다. 사무 환경에선 인텔 등의 번들 쿨러도 꽤 쓸만한 편이지만 고사양 게임을 위한 PC라면 별도의 고가 공랭식 쿨러,혹은 수랭식 쿨러를 쓰는 것이 좋습니다. 또 쿨러는 겉으로 보이는 팬의 작동 모습이나 소리 등을 통해 고장 유무가 쉽게 파악되는 부품 중 하나이며 쿨러가 고장나면 CPU에 발생하는 고열로 인해 PC가 쉽게 다운되곤 합니다.\r\n");
      out.write("</p>\r\n");
      out.write("\t\t\t<details>\r\n");
      out.write("\t\t\t\t\t<summary>추천모델</summary>\r\n");
      out.write("\t\t\t\t\t<p>일반쿨러: DEEPCOOL GAMER STORM ASSASSIN 3<br>\r\n");
      out.write("\t\t\t\t\t수랭쿨러: NZXT KRAKEN X73</p>\r\n");
      out.write("\t\t\t</details>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"image\"><img src=\"assets/images/초급 -CASE.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t<h2>케이스</h2>\r\n");
      out.write("\t\t\t<p> <i>외관 디자인 담당 & 내부 보호</i><br>\r\n");
      out.write("내부 부품을 한곳에 모아두는 박스입니다. 크기는 빅타워, 미들타워, 준슬림, 미니타워, 초슬림으로 총 5가지이며 다양한 가격대와 디자인 때문에 미들타워 케이스가 가장 대중적으로 쓰입니다. 사용용도/환경에 따라 케이스를 고르시면 되나 케이스는 저가형으로도 충분한 몫을 하는 하드웨어인 만큼 꼭 큰?비용을 투자할 필요는 없답니다.\r\n");
      out.write("</p>\r\n");
      out.write("\t\t\t<details>\r\n");
      out.write("\t\t\t\t<summary>사용범위</summary>\r\n");
      out.write("\t\t\t\t<p>빅타워: 많은 수의 하드디스크를 설치하는 시스템을 운영하거나 발열이 높은 고성능 시스템을 구성할 때 주로 사용<br>\r\n");
      out.write("\t\t\t\t미들타워: 제일 대중적으로 쓰이는 케이스<br>\r\n");
      out.write("\t\t\t\t준슬림: 미들타워보다 작은 공간 차지, 초슬림보다 넓은 확장성을 갖고있으나 좁은 공간으로 제한적<br>\r\n");
      out.write("\t\t\t\t미니타워: 시디롬 가로 장착과 ATX파워 장착이 가능하며 슬림형에 비해 공간이 넓어 확장에 용이<br>\r\n");
      out.write("\t\t\t\t초슬림: 저전력, 적은 공간 차지 그러나 업그레이드가 불가능하며 일반 규격과는 다른 부품을 사용해야함</p>\r\n");
      out.write("\t\t\t</details>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t</div>\r\n");
      out.write("    </main>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <!-- Footer Start-->\r\n");
      out.write("        <div class=\"footer-area footer-padding section-bg\" data-background=\"assets/img/gallery/footer_bg.png\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- Footer Top -->\r\n");
      out.write("                <div class=\"footer-top\">\r\n");
      out.write("                    <div class=\"row justify-content-between\">\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-3 col-md-5 col-sm-6\">\r\n");
      out.write("                            <div class=\"single-footer-caption mb-50\">\r\n");
      out.write("                                <div class=\"single-footer-caption mb-30\">\r\n");
      out.write("                                    <!-- logo -->\r\n");
      out.write("                                    <div class=\"footer-logo\">\r\n");
      out.write("                                        <a href=\"index.html\"><img src=\"assets/img/logo/logo2_footer.png\" alt=\"\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"footer-tittle\">\r\n");
      out.write("                                        <div class=\"footer-pera\">\r\n");
      out.write("                                            <p>Consectetur adipisicinhg cvelicsed do eiusmod tempor inciducvccnt ut labosvrer adipisic.</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-2 col-lg-3 col-md-3 col-sm-5\">\r\n");
      out.write("                            <div class=\"single-footer-caption mb-50\">\r\n");
      out.write("                                <div class=\"footer-tittle\">\r\n");
      out.write("                                    <h4>Quick Links</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">About</a></li>\r\n");
      out.write("                                        <li><a href=\"#\"> Offers & Discounts</a></li>\r\n");
      out.write("                                        <li><a href=\"#\"> Get Coupon</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">  Contact Us</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-3 col-md-4 col-sm-7\">\r\n");
      out.write("                            <div class=\"single-footer-caption mb-50\">\r\n");
      out.write("                                <div class=\"footer-tittle\">\r\n");
      out.write("                                    <h4>New Products</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">Woman Cloth</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Fashion Accessories</a></li>\r\n");
      out.write("                                        <li><a href=\"#\"> Man Accessories</a></li>\r\n");
      out.write("                                        <li><a href=\"#\"> Rubber made Toys</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-3 col-md-5 col-sm-7\">\r\n");
      out.write("                            <div class=\"single-footer-caption mb-50\">\r\n");
      out.write("                                <div class=\"footer-tittle\">\r\n");
      out.write("                                    <h4>Support</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">Frequently Asked Questions</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Terms & Conditions</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Report a Payment Issue</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Footer bottom -->\r\n");
      out.write("                <div class=\"footer-bottom\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xl-7 col-lg-8 col-md-7\">\r\n");
      out.write("                            <div class=\"footer-copy-right\">\r\n");
      out.write("                                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>                   \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-5 col-lg-4 col-md-5\">\r\n");
      out.write("                            <div class=\"footer-copy-right f-right\">\r\n");
      out.write("                                <!-- social -->\r\n");
      out.write("                                <div class=\"footer-social\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                    <a href=\"https://www.facebook.com/sai4ull\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fab fa-behance\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fas fa-globe\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Footer End-->\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Scroll Up -->\r\n");
      out.write("    <div id=\"back-top\" >\r\n");
      out.write("        <a title=\"Go to Top\" href=\"#\"> <i class=\"fas fa-level-up-alt\"></i></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- JS here -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./assets/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("    <!-- Jquery, Popper, Bootstrap -->\r\n");
      out.write("    <script src=\"./assets/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- Jquery Mobile Menu -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Jquery Slick , Owl-Carousel Plugins -->\r\n");
      out.write("    <script src=\"./assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/slick.min.js\"></script>\r\n");
      out.write("    <!-- One Page, Animated-HeadLin -->\r\n");
      out.write("    <script src=\"./assets/js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/animated.headline.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Date Picker -->\r\n");
      out.write("    <script src=\"./assets/js/gijgo.min.js\"></script>\r\n");
      out.write("    <!-- Nice-select, sticky -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.sticky.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- counter , waypoint,Hover Direction -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/hover-direction-snake.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- contact js -->\r\n");
      out.write("    <script src=\"./assets/js/contact.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.form.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/mail-script.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Jquery Plugins, main Jquery -->\t\r\n");
      out.write("    <script src=\"./assets/js/plugins.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
