/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-07-15 05:54:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class wordmid_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title> Architects | Template </title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link rel=\"manifest\" href=\"site.webmanifest\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- CSS here -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/hamburgers.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/gijgo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/animated-headline.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/slick.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/posts.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/logostyle.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- ? Preloader Start -->\r\n");
      out.write("    <div id=\"preloader-active\">\r\n");
      out.write("        <div class=\"preloader d-flex align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"preloader-inner position-relative\">\r\n");
      out.write("                <div class=\"preloader-circle\"></div>\r\n");
      out.write("                <div class=\"preloader-img pere-text\">\r\n");
      out.write("                    <img src=\"assets/img/logo/loder.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Preloader Start -->\r\n");
      out.write("    <div>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("    <!-- header end -->\r\n");
      out.write("    <main>\r\n");
      out.write("        <!--? Hero Start -->\r\n");
      out.write("        <div class=\"slider-area2\">\r\n");
      out.write("            <div class=\"slider-height2 d-flex align-items-center\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xl-12\">\r\n");
      out.write("                            <div class=\"hero-cap hero-cap2 pt-70 text-center\">\r\n");
      out.write("                                <h2>컴퓨터 중급 용어</h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Hero End -->\r\n");
      out.write("       <div class=\"posts\">\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<div class=\"embed-container\"><iframe width=\"520\" height=\"381.53\" src=\"https://www.youtube.com/embed/VJI88QIW7H4\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe></div><br>\r\n");
      out.write("\t\t\t<h2>오버클럭</h2>\r\n");
      out.write("\t\t\t<p>100%의 성능을 200%까지 끌어올리는 과정이며 시도 중간에 부품이 고장나는 경우도 있기 때문에 필수로 해야하는 과정은 아닙니다. 오버클럭을 하게될 시 컴퓨터의 전력을 더 소모하게 되어 소음과 발열이 발생하게됩니다.\r\n");
      out.write("</p>\r\n");
      out.write("\t\t\t<details>\r\n");
      out.write("\t\t\t\t\t<summary>조건</summary>\r\n");
      out.write("\t\t\t\t\t<p>Z가 붙은 메인보드, K가 붙은 CPU, XMP지원이 되는 램</p>\r\n");
      out.write("\t\t\t</details>\r\n");
      out.write("\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<div class=\"embed-container\"><iframe width=\"520\" height=\"381.53\" src=\"https://www.youtube.com/embed/VJI88QIW7H4\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe></div><br>\r\n");
      out.write("\t\t\t<h2>언더클럭</h2>\r\n");
      out.write("\t\t\t<p>오버클럭의 반댓말으로 클럭과 전압을 동시에 낮춰서 최대한 저소음 및 배터리 시간을 극한으로 늘리는 기술입니다. 그러나 지나친 언더클럭은 오히려 장치에 해가 되기 때문에 자주 시도하는 것은 좋지 않습니다.\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<div class=\"embed-container\"><iframe width=\"520\" height=\"381.53\" src=\"https://www.youtube.com/embed/VJI88QIW7H4\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe></div><br>\r\n");
      out.write("\t\t\t<h2>언더볼팅</h2>\r\n");
      out.write("\t\t\t<p>언더클럭과 비슷하나 노트북 쓰로틀링 현상으로 인해 사용하며?클럭은 유지시키되 최대한 전압을 낮춰 성능효율성을 늘리는 기술입니다.\r\n");
      out.write("</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<div class=\"embed-container\"><iframe width=\"520\" height=\"381.53\" src=\"https://www.youtube.com/embed/VJI88QIW7H4\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe></div><br>\r\n");
      out.write("\t\t\t<h2>윈도우 설치 및 포맷</h2>\r\n");
      out.write("\t\t\t<p>포맷 전 중요파일은 백업합니다.\r\n");
      out.write("사용하는 운영체제에 따라 설치 및 포맷방법이 다르니 유튜브를 참고해 주세요.\r\n");
      out.write("</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("    </main>\r\n");
      out.write("    <div> \r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("    <!-- Scroll Up -->\r\n");
      out.write("    <div id=\"back-top\" >\r\n");
      out.write("        <a title=\"Go to Top\" href=\"#\"> <i class=\"fas fa-level-up-alt\"></i></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- JS here -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./assets/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("    <!-- Jquery, Popper, Bootstrap -->\r\n");
      out.write("    <script src=\"./assets/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- Jquery Mobile Menu -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Jquery Slick , Owl-Carousel Plugins -->\r\n");
      out.write("    <script src=\"./assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/slick.min.js\"></script>\r\n");
      out.write("    <!-- One Page, Animated-HeadLin -->\r\n");
      out.write("    <script src=\"./assets/js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/animated.headline.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Date Picker -->\r\n");
      out.write("    <script src=\"./assets/js/gijgo.min.js\"></script>\r\n");
      out.write("    <!-- Nice-select, sticky -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.sticky.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- counter , waypoint,Hover Direction -->\r\n");
      out.write("    <script src=\"./assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/hover-direction-snake.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- contact js -->\r\n");
      out.write("    <script src=\"./assets/js/contact.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.form.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/mail-script.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Jquery Plugins, main Jquery -->\t\r\n");
      out.write("    <script src=\"./assets/js/plugins.js\"></script>\r\n");
      out.write("    <script src=\"./assets/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
