/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-07-08 02:13:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class JoinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>회원가입 화면</title>\r\n");
      out.write("\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\ttable{\r\n");
      out.write("\t\t\tmargin-left:auto; \r\n");
      out.write("\t\t\tmargin-right:auto;\r\n");
      out.write("\t\t\tborder:3px solid skyblue;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttd{\r\n");
      out.write("\t\t\tborder:1px solid skyblue\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#title{\r\n");
      out.write("\t\t\tbackground-color:skyblue\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t// 회원가입 화면의 입력값들을 검사한다.\r\n");
      out.write("\t\tfunction checkValue()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar form = document.userInfo;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif(!form.id.value){\r\n");
      out.write("\t\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(form.idDuplication.value != \"idCheck\"){\r\n");
      out.write("\t\t\t\talert(\"아이디 중복체크를 해주세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(!form.password.value){\r\n");
      out.write("\t\t\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 비밀번호와 비밀번호 확인에 입력된 값이 동일한지 확인\r\n");
      out.write("\t\t\tif(form.password.value != form.passwordcheck.value ){\r\n");
      out.write("\t\t\t\talert(\"비밀번호를 동일하게 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(!form.name.value){\r\n");
      out.write("\t\t\t\talert(\"이름을 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(!form.birthyy.value){\r\n");
      out.write("\t\t\t\talert(\"년도를 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(isNaN(form.birthyy.value)){\r\n");
      out.write("\t\t\t\talert(\"년도는 숫자만 입력가능합니다.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(form.birthmm.value == \"00\"){\r\n");
      out.write("\t\t\t\talert(\"월을 선택하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(!form.birthdd.value){\r\n");
      out.write("\t\t\t\talert(\"날짜를 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(isNaN(form.birthdd.value)){\r\n");
      out.write("\t\t\t\talert(\"날짜는 숫자만 입력가능합니다.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(!form.mail1.value){\r\n");
      out.write("\t\t\t\talert(\"메일 주소를 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(!form.phone.value){\r\n");
      out.write("\t\t\t\talert(\"전화번호를 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(isNaN(form.phone.value)){\r\n");
      out.write("\t\t\t\talert(\"전화번호는 - 제외한 숫자만 입력해주세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(!form.address.value){\r\n");
      out.write("\t\t\t\talert(\"주소를 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 취소 버튼 클릭시 첫화면으로 이동\r\n");
      out.write("\t\tfunction goFirstForm() {\r\n");
      out.write("\t\t\tlocation.href=\"MainForm.do\";\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 아이디 중복체크 화면open\r\n");
      out.write("\t\tfunction openIdChk(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\twindow.name = \"parentForm\";\r\n");
      out.write("\t\t\twindow.open(\"member/IdCheckForm.jsp\",\r\n");
      out.write("\t\t\t\t\t\"chkForm\", \"width=500, height=300, resizable = no, scrollbars = no\");\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// 아이디 입력창에 값 입력시 hidden에 idUncheck를 세팅한다.\r\n");
      out.write("\t\t// 이렇게 하는 이유는 중복체크 후 다시 아이디 창이 새로운 아이디를 입력했을 때\r\n");
      out.write("\t\t// 다시 중복체크를 하도록 한다.\r\n");
      out.write("\t\tfunction inputIdChk(){\r\n");
      out.write("\t\t\tdocument.userInfo.idDuplication.value =\"idUncheck\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<b><font size=\"6\" color=\"gray\">회원가입</font></b>\r\n");
      out.write("\t\t<br><br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 입력한 값을 전송하기 위해 form 태그를 사용한다 -->\r\n");
      out.write("\t\t<!-- 값(파라미터) 전송은 POST 방식, 전송할 페이지는 JoinPro.jsp -->\r\n");
      out.write("\t\t<form method=\"post\" action=\"MemberJoinAction.do\" \r\n");
      out.write("\t\t\t\tname=\"userInfo\" onsubmit=\"return checkValue()\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"title\">아이디</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"id\" maxlength=\"50\" onkeydown=\"inputIdChk()\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"중복확인\" onclick=\"openIdChk()\">\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"idDuplication\" value=\"idUncheck\" >\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"title\">비밀번호</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"password\" maxlength=\"50\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"title\">비밀번호 확인</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"passwordcheck\" maxlength=\"50\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"title\">이름</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"name\" maxlength=\"50\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"title\">성별</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"gender\" value=\"남\" checked>남\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"gender\" value=\"여\" >여\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"title\">생일</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"birthyy\" maxlength=\"4\" placeholder=\"년(4자)\" size=\"6\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"birthmm\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"00\">월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"01\" >1</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"02\" >2</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"03\" >3</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"04\" >4</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"05\" >5</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"06\" >6</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"07\" >7</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"08\" >8</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"09\" >9</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"10\" >10</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"11\" >11</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"12\" >12</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"birthdd\" maxlength=\"2\" placeholder=\"일\" size=\"4\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"title\">이메일</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"mail1\" maxlength=\"50\">@\r\n");
      out.write("\t\t\t\t\t\t<select name=\"mail2\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>naver.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>daum.net</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>gmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>nate.com</option>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"title\">휴대전화</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"phone\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"title\">주소</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" size=\"50\" name=\"address\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"가입\"/>  \r\n");
      out.write("\t\t\t<input type=\"button\" value=\"취소\" onclick=\"goFirstForm()\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
