DROP SEQUENCE MVCBOARDSEQ;
DROP TABLE MVCBOARD;

CREATE SEQUENCE MVCBOARDSEQ NOCACHE;

--번호, 작성자, 제목, 내용, 작성일

CREATE TABLE MVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REGDATE DATE NOT NULL
);


INSERT INTO MVCBOARD VALUES(MVCBOARDSEQ.NEXTVAL, '관리자','테스트중','테스트 1234','20/06/30');

SELECT * FROM MVCBOARD;








